#pragma once

/*
	Define all the keys used in the project
*/
#define DEFAULTDIR "./basicweb"
#define DEFAULTSERVERCONFIG "configFiles/defaultConfig.conf"
#define DEFAULTERROR "./basicweb/site/errors/error404.html"
#define PAYLOADERROR "./basicweb/site/errors/error413.html"
#define TREEINDEXPAGE "./basicweb/site/directoryListing/directoryBegin.html"
#define TREEINDEXEND "./basicweb/site/directoryListing/directoryEnd.html"
#define DELETEBEGIN "./basicweb/site/delete/deleteBegin.html"
#define DELETEEND "./basicweb/site/delete/deleteEnd.html"
#define HOSTKEY "Host:"
#define CONTENTLENGTHKEY "Content-Length:"
#define CONTENTTYPEKEY "Content-Type:"
#define CONTENTCHUNKEDKEY "Transfer-Encoding: chunked"
#define LIMIT "boundary="
#define PROTOCOL "HTTP/1.1"
#define FAVICONKEY "/favicon.ico"
#define CGI_IMAGE "/cgi-bin/generic_image"
#define CGIPYSCRIPTGET "/cgi-bin/query.py"
#define CGIPYSCRIPTPOST "/cgi-bin/upload_image.py"
#define CGIPYSCRIPTBONUS "/cgi-bin/query.pl"
#define CONNECTIONKEY "Connection:"
#define MODIFIEDSINCEKEY "If-Modified-Since:"
#define LASTMODIFIEDKEY "Last-Modified:"
#define SERVERKEY "Server:"
#define APAACHE "Apache/2.4.41 (Ubuntu)\r\n"
#define MODFIEDVALUE "just after the Chirst ,15:10:00 GMT\r\n"
#define DATEKEY "Date:"
#define BEGINCONF "Config ;"
#define BEGINSERVER "Server ;"
#define ENDCONF "ENDConfig ;"
#define DOMAINNAME "domains "
#define LISTEN "listen "
#define POSTFIX ".com"
#define NOBODY "false"
#define DELIMITTER ";"
#define LISTENPATTERN "listen %15s %d ;"
#define ENTRYKEY "entry "
#define BODYKEY "bodySize "
#define BODYPATTERN "bodySize %d ;"
#define VALUEKEY "% "
#define VALUEPATTERN "%% %d ;"
#define ERRORKEY "errors "
#define BEGINARRAY '['
#define ENDARRAY ']'
#define SEPARTOR ","
#define ROUTESKEY "Route "
#define EXTENSIONKEY ".conf"
#define METHODKEY "method "
#define GETKEY "GET"
#define POSTKEY "POST"
#define DELETEKEY "DELETE"
#define REDIRECTKEY "redirect "
#define TREEKEY "treeView "
#define TREEON "on ;"
#define TREEOFF "off ;"
#define DEFAULTPAGEKEY "defPage "
#define UPLOADKEY "uploadPath "
#define ENDROUTE "ENDRoute ;"
#define ENDSERVER "ENDServer ;"
#define TREEFOLDER "<li><span class=\"icon\">📁</span>"
#define TREEFILE "<li><span class=\"icon\">📄</span>"
#define TREELIST "<ul class=\"styled-list\">"
#define TREEEND "</ul>"
#define LISTEND "</li>"
#define KILLMSG "\nInteruption signal received, killing the server"
#define CGIFILE "/tmp/.cgi_output.txt"
#define FILENAMEEND "</h1>"
#define FILENAMESTART "<h1>Uploaded file:\n"
#define FILENAMEEND "</h1>"
#define CGIKEY "cgi-bin "
#define CGI "cgi-bin"
#define CGI_PATH "/cgi-bin/"
#define CGI_URI "/cgi"
#define CGIEXTENSION1 ".py"
#define CGIEXTENSIONBONUS ".pl"
#define CGIOK "allowed"
#define CGINOTOK "disabled"
#define CGIPROHIBITED "none"
#define PYTHONPATH "/upload_image.py"
#define PYTHONROUTE "/cgiPython"
#define PYTHONQUERY "/query.py"
#define PERLROUTE "/cgiPerl"
#define PERLQUERY "/query.pl"
#define SCRIPTSEPARATOR "?"
#define TUNNEL "/tmp/.tmp.png"
#define DELETEOPTION "<option value=\""
#define DELETEOPTIONEND "</option>"
#define FILEPREFIX "filename="
#define DELETEFILE "/delete-file"
#define TODELETE "/delete"
#define ENCODING "Transfer-Encoding:"
#define DOMAINLESS "localhost"